default: don't pin bitbake on master
Otherwise we hit errors such as:

ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
     Either fix the cause of this error or at your own risk disable the checker
     (see sanity.conf).
     Following is the list of potential problems / advisories:

     Bitbake version 1.47.0 is required and version 1.44.0 was found

Signed-off-by: Peter Griffin <peter.griffin@linaro.org>